In [76]:
import matplotlib
import matplotlib.pyplot as plt
matplotlib.use("TkAgg")
import gym
import gridworld
from gym import wrappers, logger
import numpy as np
import copy
from numpy import linalg as LA

# Play with the enviroment

types de cases du jeu : 
0 correspond à une case vide, 
1 correspond à un mur (pas de reward associé car impossible de s’y déplacer), 
2 correspond au joueur,
3 correspond à une case verte, 
4 une case jaune, 
5 une case rouge
6 une case rose.

In [31]:
env = gym.make('gridworld-v0')
env.verbose = True
env.reset()

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 3, 1],
       [1, 0, 1, 0, 5, 1],
       [1, 0, 0, 0, 2, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [6]:
env.action_space

Discrete(4)

In [7]:
action = 1
obs,reward,done,info = env.step(action)

In [10]:
reward

-0.001

In [33]:
ren = env.render()

In [22]:
states, P = env.getMDP()

In [23]:
states

['[[1, 1, 1, 1, 1, 1], [1, 0, 0, 0, 3, 1], [1, 0, 1, 0, 5, 1], [1, 0, 0, 0, 2, 1], [1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]]',
 '[[1, 1, 1, 1, 1, 1], [1, 0, 0, 0, 3, 1], [1, 0, 1, 0, 2, 1], [1, 0, 0, 0, 0, 1], [1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]]',
 '[[1, 1, 1, 1, 1, 1], [1, 0, 0, 0, 3, 1], [1, 0, 1, 0, 5, 1], [1, 0, 0, 2, 0, 1], [1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]]',
 '[[1, 1, 1, 1, 1, 1], [1, 0, 0, 0, 3, 1], [1, 0, 1, 2, 5, 1], [1, 0, 0, 0, 0, 1], [1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]]',
 '[[1, 1, 1, 1, 1, 1], [1, 0, 0, 2, 3, 1], [1, 0, 1, 0, 5, 1], [1, 0, 0, 0, 0, 1], [1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]]',
 '[[1, 1, 1, 1, 1, 1], [1, 0, 0, 0, 2, 1], [1, 0, 1, 0, 5, 1], [1, 0, 0, 0, 0, 1], [1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]]',
 '[[1, 1, 1, 1, 1, 1], [1, 0, 2, 0, 3, 1], [1, 0, 1, 0, 5, 1], [1, 0, 0, 0, 0, 1], [1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]]',
 '[[1, 1, 1, 1, 1, 1], [1, 2, 0, 0, 3, 1], [1, 0, 1, 0, 5, 1], [1, 0, 0, 0, 0, 1], [1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]]',


In [24]:
# S: {A: {[(P, S', R, Done), ...]}} 
P

{0: {0: [(0.8, 0, -0.001, False),
   (0.1, 0, -0.001, False),
   (0.1, 2, -0.001, False)],
  1: [(0.8, 1, -1, True), (0.1, 0, -0.001, False), (0.1, 2, -0.001, False)],
  2: [(0.1, 0, -0.001, False), (0.1, 1, -1, True), (0.8, 2, -0.001, False)],
  3: [(0.1, 0, -0.001, False), (0.1, 1, -1, True), (0.8, 0, -0.001, False)]},
 2: {0: [(0.8, 2, -0.001, False),
   (0.1, 0, -0.001, False),
   (0.1, 10, -0.001, False)],
  1: [(0.8, 3, -0.001, False),
   (0.1, 0, -0.001, False),
   (0.1, 10, -0.001, False)],
  2: [(0.1, 2, -0.001, False),
   (0.1, 3, -0.001, False),
   (0.8, 10, -0.001, False)],
  3: [(0.1, 2, -0.001, False),
   (0.1, 3, -0.001, False),
   (0.8, 0, -0.001, False)]},
 3: {0: [(0.8, 2, -0.001, False), (0.1, 1, -1, True), (0.1, 3, -0.001, False)],
  1: [(0.8, 4, -0.001, False), (0.1, 1, -1, True), (0.1, 3, -0.001, False)],
  2: [(0.1, 2, -0.001, False),
   (0.1, 4, -0.001, False),
   (0.8, 3, -0.001, False)],
  3: [(0.1, 2, -0.001, False), (0.1, 4, -0.001, False), (0.8, 1, -1, True

In [26]:
P.keys()

dict_keys([0, 2, 3, 4, 6, 7, 8, 9, 10])

In [29]:
P[0]

{0: [(0.8, 0, -0.001, False),
  (0.1, 0, -0.001, False),
  (0.1, 2, -0.001, False)],
 1: [(0.8, 1, -1, True), (0.1, 0, -0.001, False), (0.1, 2, -0.001, False)],
 2: [(0.1, 0, -0.001, False), (0.1, 1, -1, True), (0.8, 2, -0.001, False)],
 3: [(0.1, 0, -0.001, False), (0.1, 1, -1, True), (0.8, 0, -0.001, False)]}

In [30]:
P[0].keys()

dict_keys([0, 1, 2, 3])

In [34]:
obs

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 3, 1],
       [1, 0, 1, 0, 5, 1],
       [1, 0, 0, 0, 2, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [14]:
# get number of state from a obs
env.getStateFromObs(obs)

0

In [35]:
states[0]

'[[1, 1, 1, 1, 1, 1], [1, 0, 0, 0, 3, 1], [1, 0, 1, 0, 5, 1], [1, 0, 0, 0, 2, 1], [1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]]'

# Policy implementation

In [89]:
# Environment setting
env = gym.make('gridworld-v0')
env.verbose = True
env.reset()
states, MDP = env.getMDP()

## policy iteration

In [37]:
env.action_space

Discrete(4)

In [79]:
class PolicyIterationAgent(object):
    """The world's simplest agent!"""

    def __init__(self, states, action_space, e=0.01, gamma=0.99):
        self.action_space = action_space
        self.e = e
        self.PI = np.zeros(len(states))
        self.V = np.zeros(len(states))
        
    def train(self, MDP):
        while True:
            PI_new = np.zeros_like(self.PI)
            while True:
                # V evaluation for policy PI
                V_new = np.zeros_like(self.V)
                for state, A_table in MDP.items():
                    # for each state in v
                    action = self.PI[state]
                    s_prime_list = A_table[action]
                    for p, s_prime, r, done in s_prime_list:
                        # for each s_prime possible in state s with action PI[state]
                        V_new[state] += p * (r + self.gamma*self.V[s_prime])
                if LA.norm(self.V - V_new) < self.e:
                    break
                self.V = V_new
                
            for s in len(states):
                actions = MDP[s]
                values_a = np.zeros(len(actions))
                
                
                PI_new[s] = 
            if np.array_equal(PI_new, self.PI):
                break
            self.PI = PI_new
                
    def act(self, observation):
        return self.PI[observation]
        

IndentationError: expected an indented block (<ipython-input-79-9e9895bd7e4f>, line 22)

In [106]:
np.zeros(4)

array([0., 0., 0., 0.])

In [56]:
for m, v in MDP[0]:
    print(m)

TypeError: cannot unpack non-iterable int object

In [86]:
a = np.array([1,3])
b = np.array([1,3])

In [87]:
np.array_equal(a, b)

True

In [103]:
np.zeros((1,4))

array([[0., 0., 0., 0.]])

##  value iteration

In [64]:
for a, s_prime_list in MDP[0].items():
    print(a)
    print(s_prime_list)
    break

0
[(0.8, 0, -0.001, False), (0.1, 0, -0.001, False), (0.1, 2, -0.001, False)]


In [67]:
MDP[0][0]

[(0.8, 0, -0.001, False), (0.1, 0, -0.001, False), (0.1, 2, -0.001, False)]

In [68]:
for a,b,c,d in MDP[0][0]:
    print(a)
    break

0.8


In [70]:
a = np.zeros(len(states))

In [74]:
b = np.zeros_like(a)

In [75]:
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [78]:
LA.norm(np.array([1,2])- np.array([0,3]))

1.4142135623730951